create table todos (
  id bigint generated by default as identity primary key,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  task bytea not null
);

alter table todos enable row level security;
create policy "Anyone can view todos." on todos for
    select to anon using (true);
create policy "Anyone can create todos." on todos for
    insert with check (auth.role() = 'anon');
